services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: runmate
      POSTGRES_USER: runmate
      POSTGRES_PASSWORD: runmate
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
