name: Trigger auto deployment for runmate-go-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/runmate-go-api-AutoDeployTrigger-4a83075d-a3fb-4fb8-a9ac-8e439e81cb6b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RUNMATEGOAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUNMATEGOAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUNMATEGOAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: runmate.azurecr.io
          registryUsername: ${{ secrets.RUNMATEGOAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUNMATEGOAPI_REGISTRY_PASSWORD }}
          containerAppName: runmate-go-api
          resourceGroup: runmate
          imageToBuild: runmate.azurecr.io/runmate-go-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


